.github/actions/jira-ticket-validator.js
.github/workflows/jira-publish.yml

|                                                                                                                                                                 | User               | Total reviews | Median time to review | Total comments    |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ | ------------- | --------------------- | ----------------- |
| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | 4<br/>▀▀      | **42m**<br/>          | **21**<br/>▀▀▀▀▀▀ |
| <a …

HS-150 | Fix validation for PR title

---

core/src/main/java/pl/agh/edu/engine/Engine.java
core/src/main/java/pl/agh/edu/management/employee/work_scheduler/ReceptionScheduler.java
core/src/main/java/pl/agh/edu/management/room/RoomManager.java
core/src/main/java/pl/agh/edu/model/Room.java
core/src/test/java/model/RoomTest.java

|                                                                                                                                                                 | User               | Total reviews | Median time to review | Total comments    |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ | ------------- | --------------------- | ----------------- |
| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | 8<br/>▀▀▀     | 17h 50m<br/>▀▀        | **46**<br/>▀▀▀▀▀▀ |
| <a …

HS-181 | Zmiana nazw metod na bardziej odpowiednie

---

core/spotless.eclipseformat.xml
core/src/main/java/pl/agh/edu/actor/component/navbar/NavbarBottom.java
core/src/main/java/pl/agh/edu/actor/component/selectMenu/SelectMenu.java
core/src/main/java/pl/agh/edu/actor/component/selectMenu/SelectMenuItem.java
core/src/main/java/pl/agh/edu/actor/slider/SliderComponent.java
core/src/main/java/pl/agh/edu/enums/Frequency.java
core/src/main/java/pl/agh/edu/enums/RoomSize.java
core/src/main/java/pl/agh/edu/model/employee/Shift.java
core/src/main/java/pl/agh/edu/model/time/Time.java
desktop/spotless.eclipseformat.xml
spotless.eclipseformat.xml

|                                                                                                                                                                 | User               | Total reviews  | Median time to review | Total comments   |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ | -------------- | --------------------- | ---------------- |
| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **14**<br/>▀▀▀ | 22h 20m<br/>▀▀        | **77**<br/>▀▀▀▀▀ |
| <a …

HS-189 | Change linter for switch

---

core/src/main/java/pl/agh/edu/engine/Engine.java
core/src/main/java/pl/agh/edu/management/bank/EmployeeSalaryHandler.java

|                                                                                                                                                                 | User               | Total reviews  | Median time to review | Total comments   |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ | -------------- | --------------------- | ---------------- |
| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **18**<br/>▀▀▀ | 23h 34m<br/>▀▀        | **87**<br/>▀▀▀▀▀ |
| <a …

HS-194 | fix

---

assets/jsons/room_config.json
core/src/main/java/pl/agh/edu/engine/Engine.java
core/src/main/java/pl/agh/edu/json/data_extractor/JSONValueUtil.java
core/src/main/java/pl/agh/edu/json/data_loader/JSONRoomDataLoader.java
core/src/main/java/pl/agh/edu/management/employee/work_scheduler/ReceptionScheduler.java
core/src/main/java/pl/agh/edu/management/hotel/HotelHandler.java
core/src/main/java/pl/agh/edu/management/room/RoomManager.java
core/src/main/java/pl/agh/edu/utils/EnumPair.java
core/src/main/java/pl/agh/edu/utils/Pair.java
core/src/test/java/json/JSONDataLoaderTest.java
core/src/test/java/management/RoomManagerTest.java

|                                                                                                                                                                 | User               | Total reviews  | Median time to review | Total comments   |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ | -------------- | --------------------- | ---------------- |
| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **19**<br/>▀▀▀ | 22h 20m<br/>▀▀        | **87**<br/>▀▀▀▀▀ |
| <a …

HS-193 | Koszty budowy i zmiany rangi + przychody z pokoi

---

.mailmap

|                                                                                                                                                                 | User               | Total reviews   | Median time to review | Total comments     |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------ | --------------- | --------------------- | ------------------ |
| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **30**<br/>▀▀▀▀ | 1d 22h 29m<br/>▀▀     | **132**<br/>▀▀▀▀▀▀ |
| <a …

HS-219 | Add git email mapping

---

core/src/main/java/pl/agh/edu/actor/utils/SkinColor.java
core/src/main/java/pl/agh/edu/actor/utils/SkinSpecialColor.java

|                                                                                                                                                                 | User             | Total reviews   | Median time to review | Total comments     |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------- | --------------- | --------------------- | ------------------ |
| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇   | **32**<br/>▀▀▀▀ | 2d 1h 46m<br/>▀▀▀     | **151**<br/>▀▀▀▀▀▀ |
| <a …

HS-224 | SkinColor

---

core/src/main/java/pl/agh/edu/management/bank/BankAccountHandler.java
core/src/main/java/pl/agh/edu/model/bank/BankAccount.java
core/src/main/java/pl/agh/edu/model/bank/Credit.java
core/src/main/java/pl/agh/edu/time_command/NRepeatingTimeCommand.java
core/src/test/java/management/BankAccountHandlerTest.java
core/src/test/java/time/TimeCommandExecutorTest.java

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇   | **35**<br/>▀▀▀▀ | 1d 21h 7m<br/>▀▀      | **206**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-228 | poprawki do kredytow

---

core/src/main/java/pl/agh/edu/management/client/ClientGroupGenerationHandler.java

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇   | **38**<br/>▀▀▀▀ | 1d 15h 2m<br/>▀▀      | **215**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-231 | fixed bug

---

assets/jsons/opinion_config.json
core/src/main/java/pl/agh/edu/data/loader/JSONOpinionDataLoader.java
core/src/main/java/pl/agh/edu/engine/Engine.java
core/src/main/java/pl/agh/edu/engine/client/ClientGroupGenerationHandler.java
core/src/main/java/pl/agh/edu/engine/generator/ClientGenerator.java
core/src/main/java/pl/agh/edu/engine/opinion/OpinionHandler.java
core/src/main/java/pl/agh/edu/engine/opinion/OpinionStars.java
core/src/test/java/json/JSONDataLoaderTest.java

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇   | **40**<br/>▀▀▀▀ | 1d 15h 14m<br/>▀▀     | **235**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-218 | wpływ ocen na ilość gości

---

.github/workflows/gradle-publish.yml
build.gradle

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **42**<br/>▀▀▀▀ | 1d 11h 18m<br/>▀▀     | **294**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-240 | CI fix

---

assets/i18n/language_en.properties
assets/i18n/language_pl.properties
core/src/main/java/pl/agh/edu/engine/Engine.java
core/src/main/java/pl/agh/edu/engine/client/Client.java
core/src/main/java/pl/agh/edu/engine/client/ClientGroup.java
core/src/main/java/pl/agh/edu/engine/employee/scheduler/ReceptionScheduler.java
core/src/main/java/pl/agh/edu/engine/generator/ClientGenerator.java
core/src/main/java/pl/agh/edu/engine/opinion/Opinion.java
core/src/main/java/pl/agh/edu/engine/opinion/OpinionBuilder.java
core/src/main/java/pl/agh/edu/engine/opinion/OpinionData.java
core/src/main/java/pl/agh/edu/engine/opinion/OpinionHandler.java
core/src/main/java/pl/agh/edu/engine/opinion/bucket/EmployeesSatisfactionOpinionBucket.java
core/src/main/java/pl/agh/edu/engine/opinion/bucket/OpinionBucket.java
core/src/main/java/pl/agh/edu/engine/opinion/bucket/QueueWaitingOpinionBucket.java
core/src/main/java/pl/agh/edu/engine/opinion/bucket/RoomBreakingOpinionBucket.java
core/src/main/java/pl/agh/edu/engine/opinion/bucket/RoomCleaningOpinionBucket.java
core/src/main/java/pl/agh/edu/engine/opinion/bucket/RoomPriceOpinionBucket.java
core/src/main/java/pl/agh/edu/engine/time/Time.java

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇   | **41**<br/>▀▀▀▀ | 1d 11h 30m<br/>▀▀     | **289**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-217 | Dodano komentarze do opiniii

---

assets/jsons/bank_config.json
core/src/main/java/pl/agh/edu/data/loader/JSONBankDataLoader.java
core/src/main/java/pl/agh/edu/data/type/BankData.java
core/src/main/java/pl/agh/edu/engine/bank/BankAccount.java
core/src/main/java/pl/agh/edu/engine/bank/BankAccountDetails.java
core/src/main/java/pl/agh/edu/engine/bank/BankAccountHandler.java
core/src/main/java/pl/agh/edu/engine/hotel/HotelHandler.java
core/src/test/java/model/bank/BankAccountTest.java

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **46**<br/>▀▀▀▀ | 1d 8h 11m<br/>▀▀      | **304**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-168 | dodano możliwość zmiany BankAccountDetails

---

core/src/main/java/pl/agh/edu/engine/calendar/Calendar.java

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇   | **48**<br/>▀▀▀▀ | 1d 7h 55m<br/>▀▀      | **305**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-252 | Calendar refactor

---

core/src/main/java/pl/agh/edu/engine/opinion/Opinion.java
core/src/main/java/pl/agh/edu/engine/opinion/OpinionHandler.java
core/src/main/java/pl/agh/edu/engine/opinion/OpinionStars.java
core/src/main/java/pl/agh/edu/engine/opinion/bucket/QueueWaitingOpinionBucket.java
core/src/test/java/model/opinion/OpinionStarsTest.java

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **46**<br/>▀▀▀▀ | 1d 8h 11m<br/>▀▀      | **304**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-242 | OpinionStars range change

---

assets/jsons/attraction_config.json
core/src/main/java/pl/agh/edu/data/extractor/JSONFilePath.java
core/src/main/java/pl/agh/edu/data/loader/JSONAttractionDataLoader.java
core/src/main/java/pl/agh/edu/engine/Engine.java
core/src/main/java/pl/agh/edu/engine/advertisement/AdvertisementHandler.java
core/src/main/java/pl/agh/edu/engine/attraction/Attraction.java
core/src/main/java/pl/agh/edu/engine/attraction/AttractionHandler.java
core/src/main/java/pl/agh/edu/engine/attraction/AttractionSize.java
core/src/main/java/pl/agh/edu/engine/attraction/AttractionState.java
core/src/main/java/pl/agh/edu/engine/attraction/AttractionType.java
core/src/main/java/pl/agh/edu/engine/client/ClientGroup.java
core/src/main/java/pl/agh/edu/engine/client/ClientGroupGenerationHandler.java
core/src/main/java/pl/agh/edu/engine/client/ClientGroupModifierSupplier.java
core/src/main/java/pl/agh/edu/engine/event/ClientNumberModificationEventHandler.java
core/src/main/java/pl/agh/edu/engine/hotel/HotelHandler.java
core/src/main/java/pl/agh/edu/engine/room/RoomManager.java
core/src/test/java/json/JSONDataLoaderTest.java

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **47**<br/>▀▀▀▀ | 1d 8h 11m<br/>▀▀      | **305**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-249 | Funkcjonalność atrakcji

---

assets/i18n/language_en.properties
assets/i18n/language_pl.properties
core/src/main/java/pl/agh/edu/engine/employee/scheduler/ReceptionScheduler.java
core/src/main/java/pl/agh/edu/engine/opinion/OpinionBuilder.java
core/src/main/java/pl/agh/edu/engine/opinion/bucket/RoomBreakingOpinionBucket.java
core/src/main/java/pl/agh/edu/engine/room/RoomManager.java
core/src/test/java/management/RoomManagerTest.java

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **54**<br/>▀▀▀▀ | 1d 4h 15m<br/>▀▀      | **334**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-253 | RoomBreakingOpinionBucket fix

---

core/src/main/java/pl/agh/edu/serialization/KryoConfig.java

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **58**<br/>▀▀▀▀ | 1d 8h 27m<br/>▀▀      | **374**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-261 | Wyłączenie warningów kryo

---

core/src/main/java/pl/agh/edu/engine/event/EventHandler.java
core/src/main/java/pl/agh/edu/ui/component/button/OptionButton.java
core/src/main/java/pl/agh/edu/ui/component/modal/BaseModalWrapper.java
core/src/main/java/pl/agh/edu/ui/component/modal/ModalManager.java
core/src/main/java/pl/agh/edu/ui/component/modal/event/EventModal.java
core/src/main/java/pl/agh/edu/ui/component/modal/event/EventWrapper.java
core/src/main/java/pl/agh/edu/ui/component/modal/options/OptionModal.java
core/src/main/java/pl/agh/edu/ui/component/modal/options/OptionsWrapper.java
core/src/main/java/pl/agh/edu/ui/component/selectMenu/SelectMenu.java
core/src/main/java/pl/agh/edu/ui/component/slider/SliderComponent.java
core/src/main/java/pl/agh/edu/ui/frame/employee/HireEmployeeFrame.java
core/src/main/java/pl/agh/edu/ui/screen/main/MainScreen.java
core/src/main/java/pl/agh/edu/ui/screen/main/MainScreenInputAdapter.java
core/src/main/java/pl/agh/edu/ui/shader/BlurShader.java

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **58**<br/>▀▀▀▀ | 1d 8h 11m<br/>▀▀      | **363**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-259 | Refactor of Modals

---

.github/actions/action.yml
.github/actions/package-lock.json
.github/actions/package.json
.github/workflows/jira-publish.yml

| <a href="https://github.com/lawos98"><img src="https://avatars.githubusercontent.com/u/85324038?u=f7c1da89ab9c45271cc8493559c3e40cc89ef21b&v=4" width="32"></a> | lawos98<br/>🥇     | **59**<br/>▀▀▀▀ | 1d 8h 11m<br/>▀▀      | **374**<br/>▀▀▀▀▀▀▀ |
| <a …

HS-266 | Update for Jira CI
